title: Laura Merris
author: Laura Merris
description: 
show_excerpts: true
remote_theme: ngzhio/jekyll-theme-hamilton
location: UK
avatar: https://avatars.githubusercontent.com/u/7448403?v=4
skin: daylight
markdown: GFM
subscribe: false
paginate: 2
 
# social links
twitter_username: lauramerris
github_username: lauramerris
