theme: minima
title: Laura Merris
author: Laura Merris
description: Overview of my current projects and project updates - currently working in React Native
show_excerpts: true

# social links
twitter_username: lauramerris
github_username: lauramerris
