theme: jekyll-theme-slate
title: Laura Merris
author: Laura Merris
description: Hi, I'm Laura and this is an overview of my current development projects. I'm keeping a daily (ish) accountability blog on my progress. I'm currently working in React Native.
show_excerpts: true
remote_theme: ngzhio/jekyll-theme-hamilton


# social links
twitter_username: lauramerris
github_username: lauramerris
